import json,pathlib,zipfile,hashlib,re,gzip,xml.etree.ElementTree as E,datetime
p=pathlib.Path(__file__).parent; sha=lambda b:hashlib.sha256(b).hexdigest();z=zipfile.ZipFile(p/'card-73394-original.zip');assert z.testzip() is None
expected=json.loads((p/'expected-case-identities.json').read_text());source=json.loads((p/'card-live-source-bindings.json').read_text());completed=json.loads((p/'current-completion-and-ledgers.json').read_text());report={'schema':'industrial-produced-token-author-raw-audit-v1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'author':'/root/industrial','source':'73394d7eabc7cc3dad609b9d416102a9ecce8e4f','tree':'7e635c7ff700094d840bb64fdba7699f724cf594','run':36281753256,'attempt':1,'job':108514788125,'artifact_id':10918479379,'artifact':{'bytes':(p/'card-73394-original.zip').stat().st_size,'sha256':sha((p/'card-73394-original.zip').read_bytes()),'members':len(z.namelist()),'crc_pass':True},'xml':[],'banks':{},'source_bindings':[]}
for bank,prefix,logpath,wanted in [('focused','tmp/iw-v2-produced-token-focused-xml/','tmp/iw-v2-produced-token-focused.log',20),('broad','home/runner/','tmp/iw-v2-card-receiving.log',154)]:
 cases=[]
 for n in z.namelist():
  if n.startswith(prefix) and n.endswith('.xml'):
   r=E.fromstring(z.read(n));c=[(x.get('classname'),x.get('name')) for x in r.findall('testcase')];cases+=c
   assert len(c)==int(r.get('tests')) and all(int(r.get(k,'0'))==0 for k in ['failures','errors','skipped'])
   assert all(len(x)==0 for x in r.findall('testcase'))
   report['xml'].append({'bank':bank,'name':n,'sha256':sha(z.read(n)),'tests':len(c),'timestamp':r.get('timestamp')})
 expect=[(x['class'],x['name']) for x in expected[bank]];assert len(cases)==len(set(cases))==wanted and set(cases)==set(expect)
 log=z.read(logpath).decode();tasks=re.findall(r'^> Task (\S+:test)(?=\s|$)([^\n]*)$',log,re.M);assert all(not tail.strip() for name,tail in tasks);assert 'BUILD SUCCESSFUL' in log
 passed=sum(1 for x in log.splitlines() if x.endswith(' PASSED'));assert passed==wanted
 report['banks'][bank]={'unique_cases':wanted,'expected_case_identity_exact':True,'pass_lines':passed,'failure':0,'error':0,'skip':0,'actual_test_tasks':sorted(set(name for name,tail in tasks)),'test_task_status_suffixes':sorted(set(tail for name,tail in tasks)),'raw_log_sha256':sha(z.read(logpath)),'build_successful':True}
assert len(report['banks']['focused']['actual_test_tasks'])==3 and len(report['banks']['broad']['actual_test_tasks'])==8
report.update({'focused_overlaps_broad':True,'unique_receiving_cases':154,'original_failed18_preserved':True,'prior_failed_original_sha256':'f83ef1fcdce0dc823f16efb3be93b50e2d153c7332da1176a76f832cda2c6049'})
prov=json.loads(z.read('tmp/iw-v2-produced-token-provenance.json'));status=json.loads(z.read('tmp/iw-v2-status-provenance.json'));assert status['source_head']==report['source']==status['expected_head']
for path,h in prov['verified_source_sha256'].items():
 body=source[path]['content'].encode();assert sha(body)==h;blob=hashlib.sha1(b'blob '+str(len(body)).encode()+b'\0'+body).hexdigest();assert blob==source[path]['sha'];report['source_bindings'].append({'path':path,'sha256':h,'git_blob':blob,'independently_refetched_by_author':True})
manifest_path=next(n for n in z.namelist() if n.endswith('/produced-token-qualification-source.json'));assert sha(z.read(manifest_path))==prov['manifest_sha256'];assert len(report['source_bindings'])==12
assert z.read('tmp/iw-v2-card-snapshot.diff')==b'';report['snapshot_diff_bytes']=0
ref=json.loads(z.read('tmp/iw-v2-assay/reference-inputs.json'));after=json.loads(z.read('tmp/iw-v2-assay/reference-after.json'));equiv=json.loads(z.read('tmp/iw-v2-assay/input-equivalence.json'));gz=z.read('tmp/iw-v2-assay/relevant-oracle-inputs.jsonl.gz');assert sha(gz)==ref['subset_sha256'];rows=gzip.decompress(gz).splitlines(keepends=True);assert len(rows)==len(ref['selected_rows'])==528
for row,meta in zip(rows,ref['selected_rows']):assert sha(row)==meta['raw_line_sha256']
assert ref['whole_bulk_sha256']==after['whole_bulk_sha256'] and after['unchanged'] and equiv['same_tracked_assay_sdk_build_and_two_golden_inputs'];assert equiv['candidate']==report['source']
report['assay']={'actual_exit_codes':{},'sets':{'VOW':{'total':253,'compared':70,'agree':70,'divergent':0,'undecodable':0,'excluded_grammar':127,'excluded_unmodelled_slots':5,'excluded_cannot_fold':1,'excluded_multiface':49,'excluded_oracle_text':1},'LCI':{'total':275,'compared':54,'agree':54,'divergent':0,'undecodable':0,'excluded_grammar':185,'excluded_unmodelled_slots':0,'excluded_cannot_fold':1,'excluded_multiface':34,'excluded_oracle_text':1}},'same_reference_before_after_sha256':ref['whole_bulk_sha256'],'retained_relevant_raw_rows':528,'raw_subset_sha256':sha(gz),'raw_subset_each_row_hash_verified':True,'whole_bulk_retained':False,'unchanged_assay_sdk_build_goldens_source_receipt':True,'coverage_is_limited_to_comparable_rows':True,'text_mismatch_identification':'assay-text-mismatch-identification.json','text_mismatch_attribution':'Unchanged golden/parser inputs; Halana/Alena keyword order and Walk with the Ancestors newline grouping differ from captured Oracle input; both remain excluded; source-informed Python identification is not JVM replay.'}
for name in ['corpus','VOW','LCI']:
 ex=int(z.read('tmp/iw-v2-assay/'+name+'-exit.txt'));assert ex==0;report['assay']['actual_exit_codes'][name]=ex
control=completed['control']['content'];assert not any(x in control for x in ['Halana and Alena','Walk with the Ancestors']);report['assay']['excluded_identities_not_in_immutable_control']=True
joblog=(p/'card-complete-decoded-job.log').read_text(encoding='utf-8-sig');assert '--rerun-tasks --no-build-cache' in joblog and report['source'] in joblog
report['freshness']={'card_checkout_actual_head':report['source'],'focused_test_tasks':3,'broad_test_tasks':8,'commands_have_rerun_tasks_and_no_build_cache':True,'actual_task_lines_no_cache_up_to_date_no_source_skipped_failed':True,'focused_passes':20,'broad_passes':154,'complete_decoded_job_log_sha256':sha((p/'card-complete-decoded-job.log').read_bytes()),'build_route':'prescribed just/scripts; runner reports shlock missing and existing unlocked fallback, not a working semaphore'}
report['full_ci']={'run':36281753254,'status':completed['full_ci_run']['status'],'conclusion':completed['full_ci_run']['conclusion'],'source':report['source'],'actual_checkout':'f80ee01c1ec662fe87364551c843afb452abfc65','exact_same_tree':report['tree'],'decoded_test_log_archive_sha256':sha((p/'full-ci-decoded-test-logs.zip').read_bytes()),'seven_test_groups_passed':True,'scope':'Seven complete decoded API logs, not original full-CI XML ZIP; mtg-search/mtg-sdk/mtg-sets/mtgish-tooling tests FROM-CACHE are explicitly not fresh; engine/card corrected cases show actual PASSED lines.'}
assert report['full_ci']['conclusion']=='success'
report['official_execution']={'official_games':0,'allocations_consumed':0,'latest_ref_check_utc':completed['at'],'matching_remote_official_refs':completed['official_refs'],'current_tree_execution_ledger_matches':completed['official_tree']['matches'],'current_tree_entries':completed['official_tree']['entries'],'tree_untruncated':not completed['official_tree']['truncated']}
report['checker_note']='Initial local audit regex accidentally matched testFixtures/testClasses task prefixes; corrected to require whitespace/end after exact :test and rerun. Raw-row verification also corrected to include the original newline in its hash. No source, CI, fixture or prior evidence changed.'
report['disposition']='AUTHOR_BOUNDED_CARD_ASSAY_AUDIT_PASS_PENDING_INDEPENDENT_REVIEW_AND_RECEIVING_INTEGRATION; NO_COMPLETE_RUNTIME_OR_GAMEPLAY_ADMISSION'
(p/'card-author-artifact-audit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'audit_bytes':(p/'card-author-artifact-audit.json').stat().st_size,'sha256':sha((p/'card-author-artifact-audit.json').read_bytes()),'cases':[20,154],'source_pins':12,'raw_rows':528,'official_refs':completed['official_refs']}))
