"""Collect ordinary generated bytes; reject any unrelated card snapshot change.

This checks a deterministic qualification artifact only. It does not accept source, mint
an experimental allocation, or read any gameplay outcome.
"""
from pathlib import Path
import hashlib
import json
import re
import shutil
import subprocess


ROOT = Path(__file__).resolve().parent.parent
ARTIFACT = ROOT / "sphinx-stage-e-artifact"
SNAPSHOTS = Path("mtg-sets/src/test/resources/snapshots/cards")
EXPECTED = {"FRA": "Sphinx's Approach", "ULG": "Snap", "WWK": "Goliath Sphinx"}


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True)


def records(text):
    parts = re.split(r"(?m)^// ", text)
    return {name: body.strip() for name, body in (part.split("\n", 1) for part in parts[1:])}


ARTIFACT.mkdir(exist_ok=True)
(ARTIFACT / "generated").mkdir(exist_ok=True)
(ARTIFACT / "snapshot-diff.patch").write_text(git("diff", "--", str(SNAPSHOTS)))
allowed = {str(SNAPSHOTS / f"{code}.json") for code in EXPECTED}
changed_paths = set(git("diff", "--name-only", "--", str(SNAPSHOTS)).splitlines())
changed_paths.update(git("ls-files", "--others", "--exclude-standard", "--", str(SNAPSHOTS)).splitlines())
errors = []
if changed_paths - allowed:
    errors.append("unrelated generated snapshot paths: " + ", ".join(sorted(changed_paths - allowed)))
inventory = []
for code, expected_name in EXPECTED.items():
    path = SNAPSHOTS / f"{code}.json"
    raw = (ROOT / path).read_bytes()
    shutil.copyfile(ROOT / path, ARTIFACT / "generated" / path.name)
    old_result = subprocess.run(["git", "show", f"HEAD:{path}"], cwd=ROOT, text=True, capture_output=True)
    before = records(old_result.stdout) if old_result.returncode == 0 else {}
    after = records(raw.decode())
    changed = sorted(name for name in before.keys() | after.keys() if before.get(name) != after.get(name))
    if expected_name not in after:
        errors.append(f"{code}: exact card missing from generated snapshot: {expected_name}")
    if set(changed) - {expected_name}:
        errors.append(f"{code}: unrelated records changed: {changed}")
    inventory.append({"path": str(path), "sha256": hashlib.sha256(raw).hexdigest(), "changed_cards": changed})
report = {
    "status": "GENERATED_BYTES_REVIEW_REQUIRED" if not errors else "REJECTED_UNRELATED_SNAPSHOT_DRIFT",
    "runtime_head": git("rev-parse", "HEAD").strip(),
    "runtime_tree": git("rev-parse", "HEAD^{tree}").strip(),
    "generated_snapshots": inventory,
    "errors": errors,
    "official_seeds_generated": 0,
    "official_games_initialized": 0,
    "official_outcomes_exposed": 0,
}
(ARTIFACT / "generated-snapshot-inventory.json").write_text(json.dumps(report, indent=2) + "\n")
print(json.dumps(report, indent=2))
if errors:
    raise SystemExit(1)
